---
- name: Prepare common directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
  loop:
    - ~/.bashrc.d/
    - ~/Projects

- name: Install common packages
  become: true
  ansible.builtin.dnf:
    state: present
    name: "{{ item }}"
  loop:
    - git
    - curl
    - gnome-tweak-tool
