---
- name: Prepare fonts folder
  ansible.builtin.file:
    path: ~/.local/share/fonts/nerdfonts
    state: directory

- name: Install Hack fonts
  ansible.builtin.copy:
    src: "{{ role_path }}/files/fonts/{{ item }}"
    dest: ~/.local/share/fonts/nerdfonts
  loop:
    - "Hack Bold Italic Nerd Font Complete.ttf"
    - "Hack Bold Nerd Font Complete.ttf"
    - "Hack Italic Nerd Font Complete.ttf"
    - "Hack Regular Nerd Font Complete.ttf"
    - "Hack Regular Nerd Font Complete Mono.ttf"

- name: Configure GNOME to use the newly installed fonts
  ansible.builtin.command:
    cmd: "gsettings set {{ item.pkg }} {{ item.key }} '{{ item.value }}'"
  loop:
    - { pkg: "org.gnome.desktop.interface", key: "font-name", value: "Hack Nerd Font 11" }
    - { pkg: "org.gnome.desktop.interface", key: "document-font-name", value: "Hack Nerd Font 11" }
    - { pkg: "org.gnome.desktop.interface", key: "monospace-font-name", value: "Hack Nerd Font Mono 10" }
    - { pkg: "org.gnome.desktop.wm.preferences", key: "titlebar-font", value: "Hack Nerd Font Bold 11" }
  register: _output
  changed_when: _output.rc != 0
