---
- name: Install Hacker prefered fonts
  ansible.builtin.import_tasks: fonts.yml
  tags: [fonts]

- name: Install starship
  ansible.builtin.import_tasks: starship.yml
  tags: [starship, terminal]

- name: Install HyperJS
  ansible.builtin.import_tasks: hyperjs.yml
  tags: [hyperjs, terminal]

- name: Install VSCode
  ansible.builtin.import_tasks: vscode.yml
  tags: [vscode, editors]

- name: Copy dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  tags: [dotfiles]
