---
- name: Deploy common configuration (directories, packages, ...)
  ansible.builtin.import_tasks: common.yml
  tags: [common]

- name: Deploy ZSA configuration to recognize Moonlander keyboard
  ansible.builtin.import_tasks: zsa.yml
  tags: [common]

- name: Install Hacker prefered fonts
  ansible.builtin.import_tasks: fonts.yml
  tags: [fonts]

- name: Install starship
  ansible.builtin.import_tasks: starship.yml
  tags: [starship, terminal]

- name: Install HyperJS
  ansible.builtin.import_tasks: hyperjs.yml
  tags: [hyperjs, terminal]

- name: Install VSCode
  ansible.builtin.import_tasks: vscode.yml
  tags: [vscode, editors]

- name: Install Neovim
  ansible.builtin.import_tasks: nvim.yml
  tags: [nvim, editors]

- name: Install asdf
  ansible.builtin.import_tasks: asdf.yml
  tags: [asdf, cli]

- name: Copy dotfiles
  ansible.builtin.import_tasks: dotfiles.yml
  tags: [dotfiles]
