[tools]
"cargo:alacritty" = "latest"
"cargo:eza" = "latest"
clusterctl = "v1.12.3"
go = "latest"
helix = "latest"
helm = "latest"
kind = "latest"
kubecolor = "latest"
kubectl = "latest"
kubeswitch = "latest"
node = "latest"
rust = "latest"
starship = "latest"
terraform = "latest"
uv = "latest"
vault = "latest"
viddy = "latest"
zellij = "latest"
zoxide = "latest"
